import {
  BatteryType,
} from '@prisma/client';



export const batteries = [
    {
      brandId: 2,
      model: "DF4100 (240Ah/220Ah)",
      lifespan: 2,
      dod: 0.2,
      voltage: 12.0,
      current: 220,
      batteryType: "LEAD_ACID" as BatteryType,
    },
    {
      brandId: 2,
      model: "DF2500 (165Ah/150Ah)",
      lifespan: 2,
      dod: 0.2,
      voltage: 12.0,
      current: 150,
      batteryType: "LEAD_ACID" as BatteryType,
    },
    {
      brandId: 2,
      model: "DF2000 (115Ah/105Ah)",
      lifespan: 2,
      dod: 0.2,
      voltage: 12.0,
      current: 105.0,
      batteryType: "LEAD_ACID" as BatteryType,
    },
    {
      brandId: 2,
      model: "DF700 (50Ah/45Ah)",
      lifespan: 2,
      dod: 0.2,
      voltage: 12.0,
      current: 45.0,
      batteryType: "LEAD_ACID" as BatteryType,
    },
    {
      brandId: 2,
      model: "DF1000 (70Ah/60Ah)",
      lifespan: 2,
      dod: 0.2,
      voltage: 12.0,
      current: 60.0,
      batteryType: "LEAD_ACID" as BatteryType,
    },
    {
      brandId: 3,
      model: "12MS234 (240Ah)",
      lifespan: 2,
      dod: 0.2,
      voltage: 12.0,
      current: 240.0,
      batteryType: "LEAD_ACID" as BatteryType,
    },
    {
      brandId: 3,
      model: "12MF220 (220Ah)",
      lifespan: 2,
      dod: 0.2,
      voltage: 12.0,
      current: 220.0,
      batteryType: "LEAD_ACID" as BatteryType,
    },
    {
      brandId: 3,
      model: "12MF150 (150Ah)",
      lifespan: 2,
      dod: 0.2,
      voltage: 12.0,
      current: 150.0,
      batteryType: "LEAD_ACID" as BatteryType,
    },
    {
      brandId: 3,
      model: "12MF105 (105Ah)",
      lifespan: 2,
      dod: 0.2,
      voltage: 12.0,
      current: 105.0,
      batteryType: "LEAD_ACID" as BatteryType,
    },
    {
      brandId: 4,
      model: "S5X75HD (75Ah)",
      lifespan: 2,
      dod: 0.2,
      voltage: 12.0,
      current: 75.0,
      batteryType: "LEAD_ACID" as BatteryType,
    },
    {
      brandId: 5,
      model: "FGCL220 (220Ah)",
      lifespan: 2,
      dod: 0.2,
      voltage: 12.0,
      current: 220.0,
      batteryType: "LEAD_ACID" as BatteryType,
    },
    {
      brandId: 5,
      model: "FGCL150 (150Ah)",
      lifespan: 2,
      dod: 0.2,
      voltage: 12.0,
      current: 150.0,
      batteryType: "LEAD_ACID" as BatteryType,
    },
    {
      brandId: 6,
      model: "UPLFP48-100 (100Ah)",
      lifespan: 15,
      dod: 0.8,
      voltage: 48.0,
      current: 100.0,
      batteryType: "LITHIUM" as BatteryType,
    },
    {
      brandId: 7,
      model: "US3000 (72Ah)",
      lifespan: 15,
      dod: 0.8,
      voltage: 48.0,
      current: 72.0,
      batteryType: "LITHIUM" as BatteryType,
    },
    {
      brandId: 3,
      model: "48MLS100 (100Ah)",
      lifespan: 15,
      dod: 0.8,
      voltage: 48.0,
      current: 100.0,
      batteryType: "LITHIUM" as BatteryType,
    },
    {
      brandId: 8,
      model: "A48100 (100Ah)",
      lifespan: 15,
      dod: 0.8,
      voltage: 48.0,
      current: 100.0,
      batteryType: "LITHIUM" as BatteryType,
    },
    {
      brandId: 8,
      model: "PowerBox F-2.5 (50Ah)",
      lifespan: 15,
      dod: 0.8,
      voltage: 48.0,
      current: 50.0,
      batteryType: "LITHIUM" as BatteryType,
    },
    {
      brandId: 8,
      model: "PowerBox F-5. (100Ah)",
      lifespan: 15,
      dod: 0.8,
      voltage: 48.0,
      current: 100.0,
      batteryType: "LITHIUM" as BatteryType,
    },
    {
      brandId: 8,
      model: "PowerBox F-7.5 (150Ah)",
      lifespan: 15,
      dod: 0.8,
      voltage: 48.0,
      current: 150.0,
      batteryType: "LITHIUM" as BatteryType,
    },
    {
      brandId: 8,
      model: "PowerBox F-10.0 (200Ah)",
      lifespan: 15,
      dod: 0.8,
      voltage: 48.0,
      current: 200.0,
      batteryType: "LITHIUM" as BatteryType,
    },
    {
      brandId: 1,
      model: "BOG-G (100Ah)",
      lifespan: 15,
      dod: 0.9,
      voltage: 51.2,
      current: 100.0,
      batteryType: "LITHIUM" as BatteryType,
    },
    {
      brandId: 1,
      model: "RW.M6.1 (120Ah)",
      lifespan: 15,
      dod: 0.9,
      voltage: 51.2,
      current: 120.0,
      batteryType: "LITHIUM" as BatteryType,
    },
    {
      brandId: 1,
      model: "RW-M5.3 (104Ah)",
      lifespan: 15,
      dod: 0.9,
      voltage: 51.2,
      current: 104.0,
      batteryType: "LITHIUM" as BatteryType,
    },
    {
      brandId: 1,
      model: "SE-G5.1 PRO (100Ah)",
      lifespan: 15,
      dod: 0.9,
      voltage: 51.2,
      current: 100.0,
      batteryType: "LITHIUM" as BatteryType,
    },
]